window.TRIP = {
  "updated": "2026-09-21",
  "days": [
    {
      "id": 1,
      "date": "11.07",
      "weekday": "SAT",
      "jpWeek": "土",
      "place": "小樽・朝里",
      "region": "OTARU / ASARIGAWA",
      "title": "運河の灯りに、会いに。",
      "description": "空港でラーメンを食べて小樽へ。堺町を散策し、夕方は運河クルーズ。",
      "photo": "P03",
      "route": "新千歳 → 小樽 → 朝里川温泉",
      "anchor": "17:00 運河クルーズ",
      "anchorNote": "16:45までに乗船手続き",
      "hotel": "朝里川温泉ホテル",
      "hotelNote": "素泊まり / 翌朝のパンを小樽で",
      "hotelQuery": "朝里川温泉ホテル 小樽市朝里川温泉2-670",
      "notes": [
        {
          "title": "空港では時間を見ながら",
          "text": "11:00到着から昼食・送迎をはさんで12:00貸出は短め。荷物受取やラーメンの行列が長ければ、お店に遅れる旨を連絡。",
          "source": "https://www.j-netrentacar.co.jp/hokkaido/shinchitose_airport/",
          "label": "送迎の案内"
        },
        {
          "title": "明日の朝ごはんを忘れずに",
          "text": "小樽でパンを買ってから宿へ。翌日は美瑛まで移動が長いので、8:00出発を目安に。"
        }
      ],
      "events": [
        {
          "time": "11:00",
          "kind": "指定時刻",
          "category": "ARRIVAL",
          "title": "新千歳空港に到着",
          "text": "荷物を受け取り、国内線ターミナルへ。",
          "query": "新千歳空港 国内線ターミナル",
          "address": "千歳市美々 新千歳空港",
          "fixed": true
        },
        {
          "time": "到着後",
          "kind": "昼食",
          "category": "LUNCH",
          "title": "らーめん空 新千歳空港店",
          "text": "国内線3F・北海道ラーメン道場。通常10:00–20:00。行列とレンタカーの時間を確認して。",
          "query": "らーめん空 新千歳空港店",
          "address": "新千歳空港 国内線ターミナル3F",
          "source": "https://www.hokkaido-airports.com/ja/new-chitose/spend/shop/238/",
          "travelMode": "walking",
          "leg": "空港内を徒歩 → 店舗へは送迎バス"
        },
        {
          "time": "12:00",
          "kind": "指定時刻",
          "category": "RENTAL CAR",
          "title": "Jネットレンタカーで出発",
          "text": "空港1Fのバス停1番を過ぎた交番横の許可車乗降所から送迎。空港内にカウンターはありません。",
          "query": "Jネットレンタカー 新千歳空港店 千歳市流通3-2-8",
          "address": "千歳市流通3-2-8",
          "source": "https://www.j-netrentacar.co.jp/hokkaido/shinchitose_airport/",
          "phone": "0120302554",
          "fixed": true,
          "noDirections": true,
          "leg": "小樽まで車 約90–120分（高速利用の目安）"
        },
        {
          "time": "14:00",
          "kind": "目安",
          "category": "WALK & BREAD",
          "title": "小樽・堺町通りを散策",
          "text": "お店をのぞきながら街歩き。翌朝のパンも購入。小樽駅と堺町通りは少し離れているので、歩く時間も確保。",
          "query": "小樽堺町通り商店街",
          "address": "小樽市堺町周辺",
          "source": "https://otaru-sakaimachi.com/",
          "leg": "メルヘン交差点から乗船場まで徒歩 約20–25分"
        },
        {
          "time": "16:30",
          "kind": "集合目安",
          "category": "CHECK IN",
          "title": "中央橋の乗船場へ",
          "text": "乗船手続きは16:45まで。17:00発の便に合わせて、少し早めに到着。",
          "query": "小樽運河クルーズ 中央橋",
          "address": "小樽市港町5-4 中央橋",
          "source": "https://otaru.cc/",
          "travelMode": "walking"
        },
        {
          "time": "17:00",
          "kind": "指定時刻",
          "category": "CANAL CRUISE",
          "title": "小樽運河ナイトクルーズ",
          "text": "約40分の船旅。11月の公式時刻表でも17:00便を確認。天候による運休は当日確認。",
          "query": "小樽運河クルーズ 中央橋",
          "address": "中央橋発着 / 17:00–17:40",
          "source": "https://otaru.cc/wp-content/uploads/2026/08/2026_1101_1130.pdf",
          "fixed": true,
          "travelMode": "walking"
        },
        {
          "time": "18:00",
          "kind": "夕食の目安",
          "category": "DINNER",
          "title": "焼肉ジンギスカン 店名なし",
          "text": "送ってもらった地図のお店。通常17:00–23:00、不定休。予約時刻は未確認。",
          "query": "焼肉ジンギスカン 店名なし 小樽市花園1-2-6",
          "map": "https://maps.app.goo.gl/pMdyG7RURZGMkgHw8?g_st=ic",
          "address": "小樽市花園1-2-6",
          "source": "https://tenmeinashi.com/access.html",
          "phone": "0134211129",
          "travelMode": "walking",
          "leg": "宿まで車 約25–35分"
        },
        {
          "time": "19:30",
          "kind": "目安",
          "category": "STAY",
          "title": "朝里川温泉ホテル",
          "text": "今夜は素泊まり。チェックイン15:00–20:00、チェックアウト8:00–10:00。星を撮りに行くなら、先に宿の手続きを。",
          "query": "朝里川温泉ホテル 小樽市朝里川温泉2-670",
          "address": "小樽市朝里川温泉2-670",
          "source": "https://asarigawaonsenhotel.com/"
        }
      ]
    },
    {
      "id": 2,
      "date": "11.08",
      "weekday": "SUN",
      "jpWeek": "日",
      "place": "富良野・美瑛",
      "region": "FURANO / BIEI",
      "title": "丘を越えて、青い池へ。",
      "description": "チーズ工房や見晴らしのよい丘をめぐり、青い池を見てから宿へ。",
      "photo": "P04",
      "route": "朝里 → 富良野 → 美瑛 → 白金温泉",
      "anchor": "08:00 出発が目安",
      "anchorNote": "丘は明るいうちに / 遅れたら短縮",
      "hotel": "碧の美 ゆゆ",
      "hotelNote": "夕・朝食つき / 夕食時刻は未定",
      "hotelQuery": "碧の美 ゆゆ 美瑛町白金",
      "notes": [
        {
          "title": "チーズ工房の営業を確認",
          "text": "11月第2週に整備休業の予定があります。11/8の営業を事前確認。ピッツァは通常10:30–16:00、生地がなくなり次第終了。",
          "source": "https://www.furano-cheese.jp/",
          "label": "営業案内",
          "warning": true
        },
        {
          "title": "丘は、日があるうちに",
          "text": "就実の丘を含むコースは移動が長め。降雪後の通行・駐車可否は未確認。遅れた場合は就実の丘を短縮し、青い池と宿へ向かう案も。"
        },
        {
          "title": "白金温泉へは美瑛市街から",
          "text": "上富良野から山を越える経路は冬季閉鎖があります。国道237号で美瑛へ進み、道道966号で白金温泉へ。",
          "source": "https://www.shiroganeonsen.com/access/",
          "label": "宿のアクセス案内"
        }
      ],
      "events": [
        {
          "time": "07:00",
          "kind": "目安",
          "category": "BREAKFAST",
          "title": "昨日買ったパンで朝ごはん",
          "text": "宿で朝食を済ませ、長めのドライブに備える。",
          "query": "朝里川温泉ホテル 小樽市朝里川温泉2-670",
          "address": "朝里川温泉ホテル"
        },
        {
          "time": "08:00",
          "kind": "目安",
          "category": "DEPARTURE",
          "title": "朝里川温泉を出発",
          "text": "富良野へ。途中で一度休憩をとる想定。路面状況に合わせて時間に余裕を。",
          "query": "朝里川温泉ホテル 小樽市朝里川温泉2-670",
          "address": "朝里川温泉ホテル",
          "leg": "富良野まで車 約3–3.5時間（休憩込み）"
        },
        {
          "time": "11:30",
          "kind": "目安・要営業確認",
          "category": "LUNCH",
          "title": "富良野チーズ工房",
          "text": "工房で昼食。11月第2週の整備休業予定があるため、11/8の営業は事前に確認。",
          "query": "富良野チーズ工房",
          "address": "富良野市中五区",
          "source": "https://www.furano-cheese.jp/",
          "phone": "0167231156",
          "leg": "三愛の丘まで車 約45–60分"
        },
        {
          "time": "13:15",
          "kind": "目安",
          "category": "LANDSCAPE",
          "title": "三愛の丘展望公園",
          "text": "丘の広がりとカラマツを眺める時間。紅葉の進み方はその年次第。無料駐車場あり、冬季はトイレ使用不可。",
          "query": "三愛の丘展望公園",
          "address": "上川郡美瑛町みどり",
          "source": "https://www.biei-hokkaido.jp/ja/facility/san-ai-no-oka_view-park",
          "leg": "就実の丘まで車 約30–40分"
        },
        {
          "time": "14:15",
          "kind": "目安・道路確認",
          "category": "LANDSCAPE",
          "title": "就実の丘",
          "text": "起伏のある丘と山並み。降雪後の道路と駐車場所は直前確認。畑や農道の路肩へは入らず、条件が悪ければ見送る。",
          "query": "就実の丘 旭川市西神楽",
          "address": "旭川市西神楽就実地区",
          "source": "https://www.visit-hokkaido.jp/spot/detail_10518.html",
          "leg": "青い池まで車 約40–55分"
        },
        {
          "time": "15:30",
          "kind": "目安",
          "category": "BLUE POND",
          "title": "白金青い池",
          "text": "日中の池を見てから宿へ。駐車場8:00–21:30、普通車1,000円。夜に戻る場合、11月の点灯は17:00–21:00。",
          "query": "白金青い池 駐車場",
          "address": "上川郡美瑛町白金",
          "source": "https://town.biei.hokkaido.jp/culture/event/illuminate.html",
          "leg": "宿まで車 約5–10分"
        },
        {
          "time": "16:30",
          "kind": "目安",
          "category": "STAY",
          "title": "碧の美 ゆゆ",
          "text": "夕・朝食つき。夕食時刻は予約内容を確認。夕食つきプランの最終チェックインは19:00。",
          "query": "碧の美 ゆゆ 美瑛町白金",
          "address": "上川郡美瑛町白金温泉",
          "source": "https://www.shiroganeonsen.com/faq/",
          "phone": "0166943333"
        },
        {
          "time": "夕食後",
          "kind": "晴れたら候補",
          "category": "STARRY NIGHT",
          "title": "美瑛で星景撮影",
          "text": "旅の星景撮影はこの夜が本命。宿の夕食に合わせ、雲・路面・夜間利用を確認して選ぶ。",
          "internal": "#stars-2"
        }
      ]
    },
    {
      "id": 3,
      "date": "11.09",
      "weekday": "MON",
      "jpWeek": "月",
      "place": "江別・定山渓",
      "region": "EBETSU / JOZANKEI",
      "title": "温泉街で、ひと息。",
      "description": "トリトンで昼食をとり、定山源泉公園へ。今夜の宿は森の謌。",
      "photo": "P06",
      "route": "白金温泉 → 江別 → 定山渓",
      "anchor": "12:00 トリトンが目安",
      "anchorNote": "席予約なし / 待ち時間を確保",
      "hotel": "森の謌",
      "hotelNote": "夕・朝食つき / 夕食時刻は未定",
      "hotelQuery": "定山渓鶴雅リゾートスパ 森の謌",
      "notes": [
        {
          "title": "移動とランチにゆとりを",
          "text": "白金温泉から江別までは長距離移動。トリトンは席予約を受け付けていないため、待ち時間も見込んで出発。",
          "source": "https://toriton-kita1.jp/shop/ebetsu/",
          "label": "トリトン 江別店"
        },
        {
          "title": "温泉卵の材料は近くで",
          "text": "卵は定山渓物産館で購入。茹で時間は温度などで変わるため、お店で目安を確認。源泉公園は7:00–21:00。",
          "source": "https://jozankei.jp/contact/faq/",
          "label": "観光協会の案内"
        }
      ],
      "events": [
        {
          "time": "朝",
          "kind": "宿で朝食",
          "category": "BREAKFAST",
          "title": "ゆゆで朝ごはん",
          "text": "朝食つきプラン。提供時刻は宿で確認。",
          "query": "碧の美 ゆゆ 美瑛町白金",
          "address": "上川郡美瑛町白金温泉"
        },
        {
          "time": "08:30",
          "kind": "目安",
          "category": "DEPARTURE",
          "title": "白金温泉を出発",
          "text": "美瑛市街を経由して江別へ。休憩をとりながら移動。",
          "query": "碧の美 ゆゆ 美瑛町白金",
          "address": "碧の美 ゆゆ",
          "leg": "江別まで車 約3–3.5時間（休憩込み）"
        },
        {
          "time": "12:00",
          "kind": "目安",
          "category": "LUNCH",
          "title": "回転寿しトリトン 江別店",
          "text": "北海道のお寿司で昼食。通常11:00–22:00。混み具合に合わせて、午後の予定を調整。",
          "query": "回転寿しトリトン 江別店",
          "address": "江別市高砂町25-3",
          "source": "https://toriton-kita1.jp/shop/ebetsu/",
          "leg": "定山渓まで車 約90–120分"
        },
        {
          "time": "15:00",
          "kind": "目安",
          "category": "ONSEN EGG",
          "title": "定山源泉公園で温泉卵",
          "text": "足湯と温泉卵づくり。通常7:00–21:00。タイムズ定山渓観光駐車場から徒歩約3分。",
          "query": "定山源泉公園",
          "address": "札幌市南区定山渓温泉東3丁目",
          "source": "https://jozankei.jp/spot/66/"
        },
        {
          "time": "16:00",
          "kind": "目安",
          "category": "STAY",
          "title": "定山渓鶴雅リゾートスパ 森の謌",
          "text": "夕・朝食つき。通常チェックイン15:00、チェックアウト10:00。夕食時刻は予約内容を確認。",
          "query": "定山渓鶴雅リゾートスパ 森の謌",
          "address": "札幌市南区定山渓温泉東3丁目192",
          "source": "https://www.morino-uta.com/access/",
          "phone": "0115982671"
        },
        {
          "time": "夕食後",
          "kind": "撮影の予備日",
          "category": "STARRY NIGHT",
          "title": "宿の近くで夜空を見上げる",
          "text": "新月の夜。遠出せず撮る場合は、宿に利用できる屋外の場所を確認。温泉街の灯りも写す夜景案に。",
          "internal": "#stars-3"
        }
      ]
    },
    {
      "id": 4,
      "date": "11.10",
      "weekday": "TUE",
      "jpWeek": "火",
      "place": "支笏湖・千歳",
      "region": "SHIKOTSU / CHITOSE",
      "title": "湖の青を、旅の最後に。",
      "description": "きのこ王国と支笏湖に立ち寄り、千歳で夕食。夜の便で帰路につく。",
      "photo": "P12",
      "route": "定山渓 → 大滝 → 支笏湖 → 新千歳",
      "anchor": "20:00 新千歳空港発",
      "anchorNote": "返却は18:00–18:15を推奨",
      "hotel": "最後はスープカレー",
      "hotelNote": "SAMA 千歳店 / 夕方は17:00開店",
      "hotelQuery": "SAMA 千歳店 千歳市末広4-1-16",
      "notes": [
        {
          "title": "返却時刻は事前に調整",
          "text": "指定の返却時刻は19:00ですが、冬季の空港送迎は18:30まで。18:00–18:15の返却を目安に、店舗へ前倒しを相談。航空会社の締切も確認。",
          "source": "https://www.j-netrentacar.co.jp/hokkaido/shinchitose_airport/",
          "label": "レンタカーの公式案内",
          "warning": true
        },
        {
          "title": "SAMAは17:00から",
          "text": "夕方の営業開始に合わせて入店する案。混んでいたら搭乗までの時間を優先し、空港での夕食への変更も検討。",
          "source": "https://hb-sama.com/shopinfo/sama-chitoseten/",
          "label": "SAMA 千歳店"
        }
      ],
      "events": [
        {
          "time": "朝",
          "kind": "宿で朝食",
          "category": "BREAKFAST",
          "title": "森の謌で朝ごはん",
          "text": "朝食を食べて、出発の準備。",
          "query": "定山渓鶴雅リゾートスパ 森の謌",
          "address": "札幌市南区定山渓温泉東3丁目192"
        },
        {
          "time": "10:00",
          "kind": "目安",
          "category": "DEPARTURE",
          "title": "定山渓を出発",
          "text": "国道230号・276号方面で大滝へ。路面状況を確認して出発。",
          "query": "定山渓鶴雅リゾートスパ 森の謌",
          "address": "森の謌",
          "leg": "大滝まで車 約75–100分"
        },
        {
          "time": "11:30",
          "kind": "目安",
          "category": "LUNCH",
          "title": "きのこ王国 大滝本店",
          "text": "きのこ料理で昼食。通常9:00–18:00。",
          "query": "きのこ王国 大滝本店",
          "address": "伊達市大滝区三階滝町637-1",
          "source": "https://www.kinoko-oukoku.com/shopinfo/shop_ootaki/",
          "leg": "支笏湖温泉街まで車 約50–65分"
        },
        {
          "time": "13:00",
          "kind": "目安",
          "category": "LAKESIDE WALK",
          "title": "支笏湖を散策",
          "text": "温泉街側の湖畔から、山並みや山線鉄橋を眺める。14:30ごろまでを目安に、千歳へ。",
          "query": "支笏湖ビジターセンター",
          "address": "千歳市支笏湖温泉",
          "source": "https://shikotsukovc.sakura.ne.jp/",
          "leg": "千歳市街まで車 約40–50分"
        },
        {
          "time": "15:30",
          "kind": "自由時間",
          "category": "CHITOSE",
          "title": "千歳で買い物・ひと休み",
          "text": "SAMAの17:00開店まで余裕があれば、パンやお土産を。寄り道は返却までの時間を見ながら。",
          "internal": "#explore-4"
        },
        {
          "time": "17:00",
          "kind": "開店に合わせる案",
          "category": "DINNER",
          "title": "SAMA 千歳店",
          "text": "旅の最後はスープカレー。夕方は17:00開店。食後に給油して返却へ。",
          "query": "SAMA 千歳店 千歳市末広4-1-16",
          "address": "千歳市末広4丁目1-16",
          "source": "https://hb-sama.com/shopinfo/sama-chitoseten/",
          "leg": "店舗まで車 約15–20分 ＋ 給油・返却手続き"
        },
        {
          "time": "18:00",
          "kind": "推奨・要調整",
          "category": "CAR RETURN",
          "title": "給油・レンタカー返却",
          "text": "18:00–18:15の返却を推奨。指定時刻は19:00のままなので、事前に店舗へ相談。冬季の空港送迎は18:30まで。",
          "query": "Jネットレンタカー 新千歳空港店 千歳市流通3-2-8",
          "address": "千歳市流通3-2-8",
          "source": "https://www.j-netrentacar.co.jp/hokkaido/shinchitose_airport/",
          "phone": "0120302554",
          "leg": "送迎バス → 空港 / 搭乗手続き・保安検査"
        },
        {
          "time": "20:00",
          "kind": "指定時刻",
          "category": "DEPARTURE",
          "title": "新千歳空港から帰路へ",
          "text": "航空会社の手荷物預け・保安検査の締切を確認して、余裕を持って搭乗口へ。",
          "query": "新千歳空港 国内線ターミナル",
          "address": "千歳市美々 新千歳空港",
          "fixed": true,
          "noDirections": true
        }
      ]
    }
  ],
  "spots": [
    {
      "day": 1,
      "name": "輪厚PA（下り・札幌方面）",
      "type": "food",
      "tag": "高速休憩",
      "enRoute": true,
      "when": "新千歳→小樽。道央道で札幌へ向かう途中。",
      "detour": "高速を降りずに / 滞在15–25分",
      "address": "北広島市・道央自動車道 下り",
      "hours": "店舗ごとに営業時間が異なります。休憩・軽食の候補に。",
      "source": "https://www.driveplaza.com/sapa/1050/1050081/2/",
      "query": "輪厚PA（下り・札幌方面） 北広島市・道央自動車道 下り",
      "text": "札幌方面へ向かう途中に立ち寄り、休憩とともに軽食をとることができます。",
      "indoors": true,
      "travelMode": "driving"
    },
    {
      "day": 1,
      "name": "金山PA（上り・小樽方面）",
      "type": "food",
      "tag": "高速休憩",
      "enRoute": true,
      "when": "新千歳→小樽。札樽道の小樽方面、到着前のひと休み。",
      "detour": "高速を降りずに / 滞在10–20分",
      "address": "札幌市手稲区・札樽自動車道 上り",
      "hours": "コンビニで飲み物や軽食を。公式の営業情報を確認。",
      "source": "https://www.driveplaza.com/sapa/1510/1510016/1/shisetsu_service.html",
      "query": "金山PA（上り・小樽方面） 札幌市手稲区・札樽自動車道 上り",
      "text": "小樽方面へ向かう途中に立ち寄ることができ、コンビニが併設されています。",
      "indoors": true,
      "travelMode": "driving"
    },
    {
      "day": 1,
      "type": "food",
      "name": "小樽サンジェルマン",
      "text": "翌朝のパンを買うなら。小樽駅に立ち寄るタイミングで、好みのパンを選んでおく。",
      "detour": "小樽駅周辺 / 買い物15–25分の目安",
      "address": "小樽市稲穂2-22-15",
      "query": "小樽サンジェルマン",
      "hours": "通常7:30–20:00。売り切れ・当日の営業は確認。",
      "source": "https://www.lairbon.co.jp/hsg2509/",
      "when": "翌朝のパンを買うとき",
      "tag": "朝ごはん用",
      "indoors": true,
      "enRoute": false
    },
    {
      "day": 1,
      "type": "food",
      "name": "ルタオ パトス",
      "text": "堺町の散策途中に、チーズスイーツでひと休み。クルーズの集合に遅れない範囲で。",
      "detour": "堺町の予定ルート沿い / 30–45分の目安",
      "address": "小樽市堺町5-22",
      "query": "ルタオ パトス",
      "hours": "物販9:00–18:00 / カフェ10:00–18:00。",
      "source": "https://www.letao-brand.jp/shop/pathos/",
      "when": "堺町散策中・クルーズ前",
      "tag": "スイーツ",
      "indoors": true,
      "travelMode": "walking",
      "enRoute": false
    },
    {
      "day": 1,
      "type": "food",
      "name": "北一ホール",
      "text": "石油ランプが灯る喫茶で、温かいミルクティーや甘いものを。堺町散策の途中に座って休む候補。",
      "detour": "堺町通り沿い / 滞在30–45分の目安",
      "address": "小樽市堺町7-26",
      "query": "北一硝子 三号館 北一ホール",
      "hours": "通常9:00–17:30、注文9:30–17:00。土曜は通常ピアノ演奏なし。臨時変更は公式で確認。",
      "source": "https://kitaichiglass.co.jp/kitaichihall/",
      "indoors": true,
      "when": "堺町散策中・クルーズ前",
      "tag": "ランプの喫茶",
      "enRoute": false
    },
    {
      "day": 1,
      "type": "scenery",
      "name": "小樽オルゴール堂 本館",
      "text": "歴史ある建物と、入口の蒸気時計を見に。館内でオルゴールを眺めながら、旅の記念を探しても。",
      "detour": "メルヘン交差点 / 滞在20–30分の目安",
      "address": "小樽市住吉町4-1",
      "query": "小樽オルゴール堂 本館",
      "hours": "通常9:00–18:00、無休。専用駐車場なし。堺町散策と合わせて徒歩で。",
      "source": "https://otaru.gr.jp/shop/orgel-doh-mainbuilding",
      "indoors": true,
      "when": "堺町散策の始めに",
      "tag": "建物・街歩き",
      "travelMode": "walking",
      "enRoute": false
    },
    {
      "day": 1,
      "type": "scenery",
      "name": "北運河・運河公園",
      "text": "幅の広い北運河と石造倉庫を眺める散歩。にぎやかな堺町とは違う、小樽の港町らしい風景を。",
      "detour": "中央橋から北側へ足を延ばす / 往復散策40–60分の目安",
      "address": "小樽市色内3丁目6",
      "query": "小樽 運河公園",
      "hours": "公園の休憩棟・トイレなどは冬季閉鎖。専用駐車場なし。屋外散策のみ、雪や足元を確認。",
      "source": "https://www.city.otaru.lg.jp/docs/2021062900013/",
      "when": "早く小樽に着いたら・16:30には中央橋へ",
      "tag": "時間に余裕があれば",
      "travelMode": "walking",
      "enRoute": false
    },
    {
      "day": 1,
      "name": "田中酒造 亀甲蔵",
      "type": "food",
      "tag": "酒蔵見学",
      "enRoute": false,
      "when": "小樽到着後、堺町を歩き始める前に。",
      "detour": "南小樽へ車で立ち寄り / 滞在20–40分",
      "address": "小樽市信香町2-2",
      "hours": "通常9:00–18:00、無料駐車場あり。運転する方は試飲不可。",
      "source": "https://otaru.gr.jp/shop/tanakasyuzo-kkikogura",
      "query": "田中酒造 亀甲蔵 小樽市信香町2-2",
      "text": "一年を通して酒造りを行う蔵で、製造場の見学やお土産選びを。運転する方は試飲を控えて。",
      "indoors": true,
      "travelMode": "driving"
    },
    {
      "day": 1,
      "name": "小樽新倉屋 駅前店",
      "type": "food",
      "tag": "和菓子",
      "enRoute": false,
      "when": "小樽駅周辺で翌朝のパンを買うついでに。",
      "detour": "駅前散策と一緒に / 滞在10–20分",
      "address": "小樽市稲穂2-22-8 小樽駅前第一ビル1階",
      "hours": "土日祝は通常8:30–17:30。売り切れ・臨時変更は確認。",
      "source": "https://www.niikuraya.com/store/",
      "query": "小樽新倉屋 駅前店 小樽市稲穂2-22-8 小樽駅前第一ビル1階",
      "text": "花園だんごを取り扱っており、移動の合間に立ち寄って購入することができます。",
      "indoors": true,
      "travelMode": "walking"
    },
    {
      "day": 1,
      "name": "日本銀行旧小樽支店金融資料館",
      "type": "scenery",
      "tag": "建築・展示",
      "enRoute": false,
      "when": "堺町・運河散策の合間。17時のクルーズ前に。",
      "detour": "市街地を徒歩で / 滞在30–45分",
      "address": "小樽市色内1-11-16",
      "hours": "11月は9:30–17:00、最終入館16:30。水曜休館、入館無料。",
      "source": "https://www3.boj.or.jp/otaru-m/",
      "query": "日本銀行旧小樽支店金融資料館 小樽市色内1-11-16",
      "text": "歴史ある建築そのものを眺めながら、館内の展示を見学することができます。",
      "indoors": true,
      "travelMode": "walking"
    },
    {
      "day": 2,
      "name": "野幌PA（下り・旭川方面）",
      "type": "food",
      "tag": "高速休憩",
      "enRoute": true,
      "when": "朝里川温泉→富良野。札幌JCTから道央道へ進んだ後。",
      "detour": "高速を降りずに / 滞在10–15分",
      "address": "江別市・道央自動車道 下り",
      "hours": "飲み物や軽食の調達に。店舗の営業時間は公式で確認。",
      "source": "https://www.driveplaza.com/sapa/1050/1050131/2/shisetsu_service.html",
      "query": "野幌PA（下り・旭川方面） 江別市・道央自動車道 下り",
      "text": "ドライブの途中に立ち寄ることができ、必要な飲み物の調達が可能です。",
      "indoors": true,
      "travelMode": "driving"
    },
    {
      "day": 2,
      "name": "岩見沢SA（下り・旭川方面）",
      "type": "food",
      "tag": "高速休憩",
      "enRoute": true,
      "when": "朝里川温泉→富良野。三笠・滝川方面へ向かう途中。",
      "detour": "高速を降りずに / 滞在15–25分",
      "address": "岩見沢市・道央自動車道 下り",
      "hours": "朝の休憩候補。野幌PAと両方寄る必要はありません。店舗の時間は確認。",
      "source": "https://www.driveplaza.com/sapa/1050/1050146/2/shisetsu_service.html",
      "query": "岩見沢SA（下り・旭川方面） 岩見沢市・道央自動車道 下り",
      "text": "長距離運転の合間に立ち寄り、しっかり休憩をとるのに適したSAです。",
      "indoors": true,
      "travelMode": "driving"
    },
    {
      "day": 2,
      "name": "道の駅 スタープラザ芦別",
      "type": "food",
      "tag": "道の駅",
      "enRoute": true,
      "when": "朝里川温泉→富良野。滝川IC・国道38号経由を選ぶ場合。",
      "detour": "芦別市街で休憩 / 滞在15–30分",
      "address": "芦別市北4条東1丁目1",
      "hours": "売店は通常9:30–17:00（9–3月）。月別の営業変更を確認。三笠経由では通りません。",
      "source": "https://go-to-ashibetsu.com/media/2024/04/01/20",
      "query": "道の駅 スタープラザ芦別 芦別市北4条東1丁目1",
      "text": "滝川から富良野へ向かう途中に立ち寄れ、地元の加工品を購入できます。",
      "indoors": true,
      "travelMode": "driving"
    },
    {
      "day": 2,
      "name": "道の駅びえい 丘のくら",
      "type": "food",
      "tag": "道の駅",
      "enRoute": true,
      "when": "富良野→美瑛の丘めぐり。美瑛駅前へ立ち寄るなら。",
      "detour": "国道237号から市街へ / 滞在20–30分",
      "address": "美瑛町本町1-9-21",
      "hours": "11月は通常9:00–17:00。駐車場あり。食堂は別の営業時間。",
      "source": "https://www.biei-hokkaido.jp/ja/facility/okanokura",
      "query": "道の駅びえい 丘のくら 美瑛町本町1-9-21",
      "text": "石造倉庫を利用した土産店となっており、立ち寄って買い物が楽しめます。",
      "indoors": true,
      "travelMode": "driving"
    },
    {
      "day": 2,
      "type": "scenery",
      "name": "白ひげの滝",
      "text": "白金温泉のすぐ近く。青い川に流れ落ちる滝を橋から眺める、短い寄り道。",
      "detour": "ゆゆの近く / 散策15–25分の目安",
      "address": "上川郡美瑛町白金",
      "query": "白ひげの滝",
      "hours": "白金観光センターに無料公共駐車場。夜の点灯は日没〜21:00。",
      "source": "https://www.biei-hokkaido.jp/ja/facility/shirahige-waterfalls",
      "when": "ゆゆに着いた前後",
      "tag": "宿のすぐ近く",
      "indoors": false,
      "enRoute": false
    },
    {
      "day": 2,
      "type": "food",
      "name": "美瑛選果・選果市場",
      "text": "美瑛の野菜や加工品、おやつを探すなら。美瑛市街を通るときの買い物候補。",
      "detour": "美瑛市街 / 買い物20–30分の目安",
      "address": "上川郡美瑛町大町2丁目",
      "query": "美瑛選果 選果市場",
      "hours": "11月は通常10:00–17:00。併設レストラン・選果工房は季節休業のため対象外。",
      "source": "https://bieisenka.jp/about/",
      "when": "美瑛市街を通るとき",
      "tag": "地元のお土産",
      "indoors": true,
      "enRoute": false
    },
    {
      "day": 2,
      "type": "scenery",
      "name": "北西の丘展望公園",
      "text": "丘と大雪山連峰を見渡す展望スポット。丘めぐりを増やすなら、就実の丘との入れ替え候補にも。",
      "detour": "美瑛市街の北西側 / 滞在20–30分＋迂回移動",
      "address": "上川郡美瑛町大久保協生",
      "query": "北西の丘展望公園",
      "hours": "無料駐車場あり。積雪期は展望台閉鎖、冬季トイレなし。11月は案内所も営業期間外。",
      "source": "https://www.biei-hokkaido.jp/ja/facility/hokusei-no-oka",
      "when": "美瑛市街を通るとき・丘の入れ替え候補",
      "tag": "積雪時は展望台閉鎖",
      "enRoute": false
    },
    {
      "day": 2,
      "type": "food",
      "name": "フラノマルシェ",
      "text": "パンや軽食、富良野のお土産が集まる場所。チーズ工房が休みだった場合の昼食候補にも。",
      "detour": "富良野市街 / 買い物20–30分・食事なら45–60分の目安",
      "address": "富良野市幸町13-1",
      "query": "フラノマルシェ",
      "hours": "通常10:00–18:00。2026年の全館休業は11/9–13の掲載。訪問予定の11/8は各テナントの営業も確認。",
      "source": "https://marche.furano.jp/",
      "indoors": true,
      "when": "富良野で昼食の前後・昼食の代案",
      "tag": "パン・軽食・お土産",
      "enRoute": false
    },
    {
      "day": 2,
      "type": "food",
      "name": "道の駅びえい 白金ビルケ",
      "text": "青い池へ向かう道沿いで、お土産や飲み物を探す短い休憩。長いドライブの区切りにも。",
      "detour": "青い池の手前 / 滞在15–25分の目安",
      "address": "上川郡美瑛町白金",
      "query": "道の駅びえい 白金ビルケ",
      "hours": "11月は通常9:00–17:00、無料駐車場あり。飲食テナントの営業は別途確認。",
      "source": "https://www.biei-hokkaido.jp/en/facility/shirogane-biruke",
      "indoors": true,
      "when": "青い池に着く前",
      "tag": "短めの休憩",
      "enRoute": false
    },
    {
      "day": 2,
      "name": "フラノデリス",
      "type": "food",
      "tag": "洋菓子",
      "enRoute": false,
      "when": "チーズ工房の昼食前後、富良野を出る前に。",
      "detour": "下御料へ迂回 / 買い物15–25分、喫茶なら長めに",
      "address": "富良野市下御料2156-1",
      "hours": "通常10:00–17:00、カフェLO16:30。火・水曜定休。11/8は日曜。",
      "source": "https://www.le-nord.com/store",
      "query": "フラノデリス 富良野市下御料2156-1",
      "text": "富良野で甘いものを買うなら。午後の丘めぐりへ向かう前に、洋菓子を選ぶひとときを。",
      "indoors": true,
      "travelMode": "driving"
    },
    {
      "day": 3,
      "name": "砂川SA（上り・札幌方面）",
      "type": "food",
      "tag": "高速休憩",
      "enRoute": true,
      "when": "白金温泉→江別。旭川方面から道央道へ入るルートの場合。",
      "detour": "高速を降りずに / 滞在15–25分",
      "address": "砂川市・道央自動車道 上り",
      "hours": "富良野・三笠経由では通りません。店舗の時間は公式で確認。",
      "source": "https://www.driveplaza.com/sapa/1050/1050166/1/shisetsu_service.html",
      "query": "砂川SA（上り・札幌方面） 砂川市・道央自動車道 上り",
      "text": "旭川を経由して移動する場合に立ち寄り、休憩をとることができるSAです。",
      "indoors": true,
      "travelMode": "driving"
    },
    {
      "day": 3,
      "name": "岩見沢SA（上り・札幌方面）",
      "type": "food",
      "tag": "高速休憩",
      "enRoute": true,
      "when": "白金温泉→江別。道央道を札幌方面へ、江別到着の前に。",
      "detour": "高速を降りずに / 滞在10–20分",
      "address": "岩見沢市・道央自動車道 上り",
      "hours": "昼食はトリトンなので、飲み物と短い休憩を中心に。店舗の時間は確認。",
      "source": "https://www.driveplaza.com/sapa/1050/1050146/1/shisetsu_service.html",
      "query": "岩見沢SA（上り・札幌方面） 岩見沢市・道央自動車道 上り",
      "text": "江別の手前で立ち寄り、移動の合間に休憩をとることができるSAです。",
      "indoors": true,
      "travelMode": "driving"
    },
    {
      "day": 3,
      "name": "八剣山キッチン＆マルシェ",
      "type": "food",
      "tag": "地元の味",
      "enRoute": true,
      "when": "江別→定山渓。国道230号から砥山方面へ入る寄り道。",
      "detour": "幹線から迂回 / 買い物20–30分",
      "address": "札幌市南区砥山194-1",
      "hours": "通常10:00–17:00。冬季不定休のため11/9の営業を確認。運転者は飲酒不可。",
      "source": "https://jozankei.jp/store/hakkenzan-kitchen/",
      "query": "八剣山キッチン＆マルシェ 札幌市南区砥山194-1",
      "text": "地元の加工品を取り扱っており、立ち寄って買い物をすることができます。",
      "indoors": true,
      "travelMode": "driving"
    },
    {
      "day": 3,
      "type": "scenery",
      "name": "二見吊橋",
      "text": "赤い橋と渓谷を眺める温泉街の散策。明るいうちに、足元がよければ少し足を延ばす。",
      "detour": "源泉公園から周辺散策 / 30–45分の目安",
      "address": "札幌市南区定山渓温泉西4丁目",
      "query": "定山渓 二見吊橋",
      "hours": "通年・無料。積雪や凍結時は無理をせず、現地の規制に従う。",
      "source": "https://jozankei.jp/spot/105/",
      "when": "源泉公園と合わせて・日没前",
      "tag": "渓谷散歩",
      "indoors": false,
      "travelMode": "walking",
      "enRoute": false
    },
    {
      "day": 3,
      "type": "food",
      "name": "雨ノ日と雪ノ日",
      "text": "ジェラートや飲み物で、温泉前の小休憩。夕食に響かないくらいの寄り道に。",
      "detour": "定山渓温泉街 / 20–40分の目安",
      "address": "札幌市南区定山渓温泉西2-41",
      "query": "雨ノ日と雪ノ日 定山渓",
      "hours": "通常10:00–18:00、木曜定休。旅行日は月曜日。",
      "source": "https://jozankei.jp/store/amenohi-yukinohi/",
      "when": "源泉公園の前後・夕食前",
      "tag": "ジェラート",
      "indoors": true,
      "enRoute": false
    },
    {
      "day": 3,
      "type": "food",
      "name": "NOPPORO COFFEE（EBRI）",
      "text": "赤レンガの商業施設で、自家焙煎コーヒーを。トリトンのあと、移動前にひと息つく候補。",
      "detour": "江別・野幌エリア / 滞在20–40分＋市内移動",
      "address": "江別市東野幌町 EBRI館内",
      "query": "NOPPORO COFFEE EBRI 江別",
      "hours": "通常10:00開店、LO18:30。テイクアウトあり。館内店舗ごとの休業は公式で確認。",
      "source": "https://www.ebri-nopporo.com/nopporocoffee/",
      "indoors": true,
      "when": "トリトンのあと・定山渓へ出発する前",
      "tag": "コーヒー休憩",
      "enRoute": false
    },
    {
      "day": 3,
      "type": "scenery",
      "name": "定山渓大橋",
      "text": "橋の上から温泉街と渓谷を見渡す、短い写真散歩。二見吊橋とどちらかを選んでも。",
      "detour": "定山渓温泉街 / 徒歩移動込み30–40分の目安",
      "address": "札幌市南区定山渓温泉東2丁目",
      "query": "定山渓大橋",
      "hours": "観光駐車場から徒歩約15分。橋の上の駐停車や近隣施設への無断駐車は不可。明るいうちに。",
      "source": "https://jozankei.jp/spot/612/",
      "when": "源泉公園の前後・日没前",
      "tag": "渓谷の写真スポット",
      "travelMode": "walking",
      "enRoute": false
    },
    {
      "day": 3,
      "type": "scenery",
      "name": "岩戸観音堂",
      "text": "温泉街の小さな歴史散策。観音堂の奥に続く洞窟で、三十三体の観音像をめぐる。",
      "detour": "源泉公園周辺 / 滞在15–25分＋徒歩移動",
      "address": "札幌市南区定山渓温泉西4丁目",
      "query": "定山渓 岩戸観音堂",
      "hours": "観光協会案内は7:00–20:00、通年。洞窟拝観は大人300円。足元に注意し、現地の案内に従う。",
      "source": "https://jozankei.jp/spot/165/",
      "indoors": true,
      "when": "源泉公園と合わせて",
      "tag": "歴史散策",
      "travelMode": "walking",
      "enRoute": false
    },
    {
      "day": 3,
      "name": "定山渓神社",
      "type": "scenery",
      "tag": "参拝・散策",
      "enRoute": false,
      "when": "温泉街に着いたら、源泉公園の前後に短い参拝。",
      "detour": "温泉街を徒歩で / 滞在10–20分",
      "address": "札幌市南区定山渓温泉東3丁目",
      "hours": "明るい時間に。神職は常駐していません。積雪時は階段の足元を確認。",
      "source": "https://jozankei.jp/spot/181/",
      "query": "定山渓神社 札幌市南区定山渓温泉東3丁目",
      "text": "温泉街の歴史に触れる、短い参拝。源泉公園と合わせて、明るいうちに歩いてみて。",
      "indoors": false,
      "travelMode": "walking"
    },
    {
      "day": 3,
      "name": "足のふれあい太郎の湯",
      "type": "scenery",
      "tag": "足湯",
      "enRoute": false,
      "when": "源泉公園から温泉街を歩くとき。宿へ入る前の小休憩。",
      "detour": "温泉街を徒歩で / 滞在15–25分",
      "address": "札幌市南区定山渓温泉東3丁目",
      "hours": "通常7:00–20:00、無料。屋根付きの屋外足湯。タオルを持参。",
      "source": "https://jozankei.jp/oneday/taro-no-yu/",
      "query": "足のふれあい太郎の湯 札幌市南区定山渓温泉東3丁目",
      "text": "屋根付きの足湯で、散策の足をひと休み。手持ちのタオルがあると便利。",
      "indoors": false,
      "travelMode": "walking"
    },
    {
      "day": 4,
      "name": "道の駅 望羊中山",
      "type": "food",
      "tag": "峠の休憩",
      "enRoute": true,
      "when": "定山渓→大滝。国道230号・中山峠を越える途中。",
      "detour": "幹線沿い / 滞在15–25分",
      "address": "喜茂別町字川上345",
      "hours": "11–3月は売店・テイクアウト9:00–17:00（LO16:45）。峠の路面・視界を確認。",
      "source": "https://ageimo.com/access",
      "query": "道の駅 望羊中山 喜茂別町字川上345",
      "text": "中山峠の休憩に、名物のあげいもを。昼のきのこ料理も楽しめるよう、軽めのおやつに。",
      "indoors": true,
      "travelMode": "driving"
    },
    {
      "day": 4,
      "name": "郷の駅 ホッときもべつ",
      "type": "food",
      "tag": "直売・お土産",
      "enRoute": true,
      "when": "中山峠→大滝。喜茂別市街を通るルートなら。",
      "detour": "市街地で小休憩 / 滞在15–25分",
      "address": "喜茂別町字喜茂別306-3",
      "hours": "通常10:00–16:00、月により変更・冬季不定休。通過時刻と営業を確認。",
      "source": "https://kimobetsu-kankou.com/information/76/",
      "query": "郷の駅 ホッときもべつ 喜茂別町字喜茂別306-3",
      "text": "特産品を取り扱っており、移動の合間に立ち寄って買い物ができます。",
      "indoors": true,
      "travelMode": "driving"
    },
    {
      "day": 4,
      "name": "青葉公園",
      "type": "scenery",
      "tag": "森の散策",
      "enRoute": true,
      "when": "支笏湖→千歳市街。道道16号から公園入口へ。",
      "detour": "市街地手前でひと歩き / 滞在20–30分",
      "address": "千歳市 青葉公園",
      "hours": "日没前の短い散策向け。積雪・園内規制・駐車場の利用状況を確認。",
      "source": "https://www.city.chitose.lg.jp/c10/1002552/1002613/1003677.html",
      "query": "青葉公園 千歳市 青葉公園",
      "text": "周囲が明るい時間帯に立ち寄って、短い森林散策を行うことができます。",
      "indoors": false,
      "travelMode": "driving"
    },
    {
      "day": 4,
      "type": "scenery",
      "name": "山線鉄橋",
      "text": "支笏湖の青に映える赤い橋。湖畔散策と合わせて、旅の最後の一枚を。",
      "detour": "支笏湖散策の中で / 15–20分の目安",
      "address": "千歳市支笏湖温泉",
      "query": "支笏湖 山線鉄橋",
      "hours": "温泉街側の湖畔から徒歩。追加の車移動は不要。",
      "source": "https://shikotsukovc.sakura.ne.jp/sansaku/shikotsu.en.html",
      "when": "支笏湖の散策中",
      "tag": "追加の車移動なし",
      "indoors": false,
      "travelMode": "walking",
      "enRoute": false
    },
    {
      "day": 4,
      "type": "food",
      "name": "ドレモルタオ",
      "text": "千歳でパンやお菓子のお土産を。SAMAの夕方開店までの買い物候補。",
      "detour": "千歳市街 / 買い物20–30分の目安",
      "address": "千歳市朝日町6丁目1-1",
      "query": "ドレモルタオ",
      "hours": "火曜は物販10:00–17:00。カフェ11:00–17:00、パンケーキLO16:00。",
      "source": "https://www.letao-brand.jp/shop/doremo/",
      "when": "千歳に戻ってから・17時前",
      "tag": "パン・スイーツ",
      "indoors": true,
      "enRoute": false
    },
    {
      "day": 4,
      "type": "scenery",
      "name": "三階滝公園",
      "text": "三段に流れる滝を眺める、大滝エリアの寄り道。開園と足元の状態を確認できたときだけ候補に。",
      "detour": "きのこ王国の前後 / 滞在20–30分＋迂回移動",
      "address": "伊達市大滝区三階滝町",
      "query": "三階滝公園 伊達市",
      "hours": "冬季休園。11/10の開園・駐車場利用は大滝総合支所へ直前確認（0142-82-6748）。閉鎖時は立ち寄らない。",
      "source": "https://date-kanko.jp/spot/022/",
      "when": "大滝での昼食前後・開園を確認できたら",
      "tag": "要開園確認",
      "enRoute": false
    },
    {
      "day": 4,
      "type": "scenery",
      "name": "支笏湖ビジターセンター",
      "text": "湖や火山、生き物の展示を見ながら、湖畔散策の予習を。寒い日には館内の見学を長めにしても。",
      "detour": "予定の支笏湖散策と同じ場所 / 見学20–40分の目安",
      "address": "千歳市支笏湖温泉番外地",
      "query": "支笏湖ビジターセンター",
      "hours": "11月は通常9:00–17:30。火曜休館は12〜3月のため、11/10は通常の休館日に当たりません。",
      "source": "https://shikotsukovc.sakura.ne.jp/vc.en.html",
      "indoors": true,
      "when": "支笏湖の散策前・寒い日の代案",
      "tag": "自然の展示",
      "travelMode": "walking",
      "enRoute": false
    },
    {
      "day": 4,
      "type": "food",
      "name": "道の駅 サーモンパーク千歳",
      "text": "千歳で地元の食品やパンを探すなら。夕食前なので、軽い買い物や持ち帰りを中心に。",
      "detour": "千歳市街 / 買い物20–30分＋市内移動",
      "address": "千歳市花園2丁目4-2",
      "query": "道の駅 サーモンパーク千歳",
      "hours": "施設は通常9:00–17:00。飲食店は早めに終了する店あり。パンは売り切れ次第終了。",
      "source": "https://www.salmonpark.com/",
      "indoors": true,
      "when": "支笏湖から千歳へ戻ったあと・17時前",
      "tag": "パン・お土産",
      "enRoute": false
    },
    {
      "day": 4,
      "name": "パティシエ・ラボ",
      "type": "food",
      "tag": "湖畔のおやつ",
      "enRoute": false,
      "when": "支笏湖散策の後、千歳市街へ出発する前に。",
      "detour": "湖畔散策と一緒に / 滞在15–25分",
      "address": "千歳市支笏湖温泉 水の謌",
      "hours": "11–4月は通常9:00–16:30。テイクアウトのスイーツや飲み物を。",
      "source": "https://www.mizunouta.com/facilities/lab/",
      "query": "パティシエ・ラボ 千歳市支笏湖温泉 水の謌",
      "text": "湖畔を散策したあとに立ち寄り、焼菓子を購入することができます。",
      "indoors": true,
      "travelMode": "walking"
    },
    {
      "day": 4,
      "name": "サケのふるさと千歳水族館",
      "type": "scenery",
      "tag": "水中観察",
      "enRoute": false,
      "when": "千歳市街に着いてから。サーモンパークでの買い物と組み合わせて。",
      "detour": "市街地へ立ち寄り / 滞在45–60分",
      "address": "千歳市花園2-312",
      "hours": "通常9:00–17:00。冬季短縮・休館は公式で再確認。SAMAの17時開店に間に合うように。",
      "source": "https://chitose-aq.jp/",
      "query": "サケのふるさと千歳水族館 千歳市花園2-312",
      "text": "千歳川の水中観察を行うことができ、川の中の様子を見学できる施設です。",
      "indoors": true,
      "travelMode": "driving"
    }
  ],
  "stars": [
    {
      "day": 1,
      "name": "祝津パノラマ展望台",
      "tag": "海と空を写す候補",
      "text": "海岸線と空を見渡す展望台。港や灯台の光を生かした星景向きの候補。風が強い日は見送る。",
      "travel": "朝里川温泉ホテルから車 約30–40分 / 片道の目安",
      "address": "小樽市祝津3丁目",
      "query": "祝津パノラマ展望台",
      "access": "駐車10台、トイレなし。夜間の駐車利用・積雪状況は直前確認。20:00までのホテルチェックインを先に済ませる。",
      "source": "https://www.city.otaru.lg.jp/docs/2020100900664/"
    },
    {
      "day": 2,
      "name": "美瑛の丘で、ガイドと星空へ",
      "tag": "第2夜の本命",
      "featured": true,
      "text": "美瑛に宿泊する人向けの貸切星空ツアー。星景撮影を中心にした内容も相談できます。撮影地は当日の空に合わせてガイドが選定。",
      "travel": "9〜4月は20:00開始 / 送迎込み約2時間以内",
      "address": "撮影地はガイドが選定",
      "access": "2名で12,000円の掲載料金。ゆゆへの送迎・夕食との時間・空き状況を事前相談。予約は未手配。",
      "source": "https://www.biei-hokkaido.jp/ja/facility/star_watching",
      "sourceLabel": "公式ツアー・相談先"
    },
    {
      "day": 2,
      "name": "三愛の丘展望公園",
      "tag": "自分たちで行くなら",
      "text": "昼間に立ち寄る丘を、夜の撮影候補にも。広い空と丘の輪郭を写すなら、まず昼のうちに駐車場所と道を確認。",
      "travel": "ゆゆから車 約25–35分 / 片道の目安",
      "address": "上川郡美瑛町みどり",
      "query": "三愛の丘展望公園",
      "access": "無料駐車場あり。夜間の利用・除雪・ゲートの状況は未確認。観光協会に確認し、畑や農道の路肩には入らない。冬季トイレ利用不可。",
      "source": "https://www.biei-hokkaido.jp/ja/facility/san-ai-no-oka_view-park",
      "phone": "0166924378"
    },
    {
      "day": 2,
      "name": "青い池のライトアップ",
      "tag": "宿の近くの予備案",
      "text": "暗い星空そのものより、ライトアップされた池と夜空を写す候補。長い移動を避けたいときに。",
      "travel": "ゆゆから車 約5–10分 / 片道の目安",
      "address": "上川郡美瑛町白金",
      "query": "白金青い池 駐車場",
      "access": "今季は2026/10/22〜2027/4/21。11月の点灯17:00–21:00、駐車場8:00–21:30。普通車1,000円/回。21:00までに撮影を終えて退出。",
      "source": "https://town.biei.hokkaido.jp/culture/event/illuminate.html"
    },
    {
      "day": 3,
      "travelMode": "walking",
      "name": "森の謌・温泉街の近くで",
      "tag": "第3夜の予備案",
      "text": "夕食後に短く撮るなら、まず宿に使える屋外の場所を相談。温泉街は灯りが多く、星の数より夜の雰囲気を写す案。",
      "travel": "宿の屋外なら車移動なし / 源泉公園へ徒歩 約10–15分",
      "address": "札幌市南区定山渓温泉東3丁目",
      "query": "定山源泉公園",
      "access": "宿の敷地利用や三脚の設置は許可を確認。源泉公園は7:00–21:00。近隣の暗い撮影地の夜間アクセスは未確認。",
      "source": "https://jozankei.jp/contact/faq/"
    }
  ],
  "sources": [
    [
      "Jネットレンタカー・冬季送迎と店舗住所",
      "https://www.j-netrentacar.co.jp/hokkaido/shinchitose_airport/"
    ],
    [
      "小樽運河クルーズ・2026年11月時刻表",
      "https://otaru.cc/wp-content/uploads/2026/08/2026_1101_1130.pdf"
    ],
    [
      "富良野チーズ工房・営業案内",
      "https://www.furano-cheese.jp/"
    ],
    [
      "美瑛町・青い池駐車場の料金と時間",
      "https://town.biei.hokkaido.jp/culture/event/news/bluepondpaidparking.html"
    ],
    [
      "美瑛町・2026–27年ライトアップ",
      "https://town.biei.hokkaido.jp/culture/event/illuminate.html"
    ],
    [
      "国立天文台・2026年月の満ち欠け",
      "https://eco.mtk.nao.ac.jp/koyomi/yoko/2026/rekiyou263.html"
    ],
    [
      "国立天文台・札幌の2026年11月の月出入",
      "https://eco.mtk.nao.ac.jp/koyomi/dni/2026/m0011.html"
    ],
    [
      "美瑛観光協会・星空観察体験",
      "https://www.biei-hokkaido.jp/ja/facility/star_watching"
    ]
  ],
  "photos": [
    {
      "id": "P03",
      "day": 1,
      "label": "小樽運河・青い夕空",
      "author": "Tan Wei Liang Byorn",
      "date": "2019年8月10日",
      "note": "夕空と倉庫の灯り。夏撮影のため、蔦の緑は旅行時期と異なる。",
      "source": "https://commons.wikimedia.org/wiki/File:Otaru_Canal_HDR1.jpg",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
    },
    {
      "id": "P04",
      "day": 2,
      "label": "青い池・横構図",
      "author": "lumoplank",
      "date": "2025年10月6日",
      "note": "青い水面と秋の木々。日別の見出しや風景カードに。",
      "source": "https://commons.wikimedia.org/wiki/File:Biei6073_-_54989988739.jpg",
      "license": "CC0",
      "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en"
    },
    {
      "id": "P06",
      "day": 3,
      "label": "定山渓・温泉街と紅葉",
      "author": "t-konno",
      "date": "2015年10月21日",
      "note": "温泉街の全景。10月の紅葉写真で、11月の状態を示すものではない。",
      "source": "https://commons.wikimedia.org/wiki/File:%E5%AE%9A%E5%B1%B1%E6%B8%93%E5%A4%A7%E6%A9%8B%EF%BC%88Jozankei_Ohashi%EF%BC%89_-_panoramio.jpg",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"
    },
    {
      "id": "P12",
      "day": 4,
      "label": "支笏湖・湖面と風不死岳",
      "author": "663highland",
      "date": "2009年10月10日",
      "note": "水面の光と山の輪郭。落ち着いた青系の写真。",
      "source": "https://commons.wikimedia.org/wiki/File:Lake_Shikotsu_Mt_Fuppushi01bs4272.jpg",
      "license": "CC BY 2.5",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.5"
    }
  ],
  "detourTips": [
    "空港から小樽への途中は、輪厚PAか金山PAで短く休憩。小樽ではカフェやパン屋から1〜2件を。16:45の乗船受付に余裕を持って戻ろう。",
    "移動の長い日。道中の休憩1件＋富良野・美瑛で1件くらいが目安。芦別は滝川IC経由の場合の候補。昼食や宿への到着が遅れそうなら、近場の白金ビルケ・白ひげの滝を優先。",
    "砂川SAは旭川経由の場合だけ。江別の昼食後は、八剣山の買い物か定山渓の短い散策から選んで。寄り道は1〜2件に絞り、宿の夕食時間を優先。",
    "中山峠・喜茂別の休憩は昼食前、支笏湖では湖畔散策とおやつを。千歳で水族館を見るなら早めに移動し、17時のSAMAと給油・返却の時間を確保。"
  ]
};
