'use strict';
const C = window.COURSE;
const lessons = C.chapters.flatMap(c => c.lessons.map(l => ({...l, chapter:c.title, setup:c.setup})));
const localMode=['localhost','127.0.0.1'].includes(location.hostname);
const key='hplc-python-learning-v1';
const state={page:'home',done:new Set(),menu:false,storage:true};
try{const saved=JSON.parse(localStorage.getItem(key)||'[]'); if(Array.isArray(saved))state.done=new Set(saved.filter(id=>lessons.some(l=>l.id===id)));}catch(e){state.storage=false;}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(id,text)=>`<a href="#${id}">${text}</a>`;
let codeIndex=0;
function code(s,label='Python'){const id=`code-${++codeIndex}`;return `<div class="code-box"><div class="code-head"><span>${label}</span><button class="copy" data-copy="${id}" aria-label="${label}のコードをコピー">コピー</button></div><pre tabindex="0"><code id="${id}">${esc(s)}</code></pre></div>`;}
function list(xs){return `<ul>${xs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;}
function announce(s){document.querySelector('#status').textContent=s;}
function navHTML(){return `<p class="nav-top">LEARNING GUIDE</p>${link('home','学習の全体像')}<p class="progress-label">完了 ${state.done.size} / ${lessons.length} レッスン</p><progress value="${state.done.size}" max="${lessons.length}" aria-label="学習の進捗"></progress>${C.chapters.map((c,i)=>`<p class="nav-chapter">${String(i).padStart(2,'0')}　${esc(c.title)}</p>${c.lessons.map(l=>`<a href="#${l.id}" ${state.page===l.id?'aria-current="page"':''}><span class="nav-id">${l.id}</span>${esc(l.title)}${state.done.has(l.id)?' ✓ 完了':''}</a>`).join('')}`).join('')}<p class="nav-chapter">困ったとき・教材</p>${link('python','Pythonの補足')}${link('data','データと用語')}${link('downloads','教材ダウンロード')}${link('start','環境構築とJupyterLab')}`;}
function home(){return `<section class="hero"><span class="eyebrow">手を動かして、分析を自分の力に。</span><h1>測定データから、<br>Pythonを学ぼう。</h1><p class="lead">CSVを開くところから、グラフづくり、予測モデルまで。架空のHPLC・生薬分析データを使い、ひとつずつ試す日本語の学習教材です。</p><div class="actions"><a class="button primary" href="#PREP-01">学習を始める →</a><a class="button" href="#PD-01">pandasの最初の体験へ</a></div><small>Pythonの基本文法を少し知っている方へ ／ 1レッスン20〜40分 ／ 全${lessons.length}レッスン</small></section><section><h2>ひとつのデータを、5つの道具で。</h2><div class="route"><div><span>01</span><b>pandas</b>表を整える</div><div><span>02</span><b>NumPy</b>数値を計算する</div><div><span>03</span><b>Matplotlib</b>図の細部を整える</div><div><span>04</span><b>seaborn</b>分布・関係を見る</div><div><span>05</span><b>scikit-learn</b>予測を確かめる</div></div><h2>読む → 動かす → 解く → 理由を確かめる</h2><p>まず${link('start','環境構築')}を済ませ、サイトとJupyterLabを並べて開きます。各ページの例題を試したら、<code>exercises.ipynb</code>で同じ演習IDを探しましょう。解答は${link('downloads','解答Notebook')}を自分で開いて確認します。</p><p class="note">教材全体でNotebookは2ファイル。各章の準備セルを実行すれば、前の章が未回答でも続けられます。Pythonの文法は使う直前に説明し、${link('python','補足ページ')}でも復習できます。</p></section><h2>学習の道順</h2><ol class="course-list">${C.chapters.map((c,i)=>`<li><a href="#${c.lessons[0].id}"><span class="course-number">${String(i).padStart(2,'0')}</span><span><strong>${esc(c.title)}</strong><small>${c.lessons.length}レッスン · 約${c.lessons.reduce((s,l)=>s+l.minutes,0)}分</small></span><span aria-hidden="true">→</span></a></li>`).join('')}</ol><p class="muted">学習完了はこのブラウザ内に保存されます。ブラウザやポートを変えると引き継がれません。</p>`;}
function lessonHTML(l){const n=lessons.findIndex(x=>x.id===l.id);return `<span class="eyebrow">${esc(l.chapter)} / ${l.id}</span><h1>${esc(l.title)}</h1><div class="meta"><span class="tag">目安 ${l.minutes}分</span><span class="tag">演習 ${l.id}</span></div><p><strong>前提知識：</strong>${esc(l.prerequisites)}</p><section class="goals"><h2>このレッスンでできること</h2>${list(l.goals)}</section>${l.explanation_html}<details><summary>この章の準備セルを表示</summary><p>JupyterLabで教材フォルダのNotebookを開き、このコードを最初に実行します。前の章の回答は不要です。</p>${code(l.setup,'章の準備')}</details><h2>例題を動かす</h2><p class="muted">これは学習用の例題です。下の演習とは条件が異なります。</p>${code(l.example)}<p class="output-label">実行結果（同梱データで検証済み）</p><div class="output" tabindex="0">${l.output_html}</div><p>${esc(l.reading)}</p><h2>よくある間違い</h2>${list(l.mistakes)}<section class="exercise"><h2>演習 ${l.id}</h2><p>${esc(l.exercise.prompt)}</p><p><code>exercises.ipynb</code>で <strong>${l.id}</strong> を検索し、この章の準備セル→TODOセル→自己確認セルの順に実行します。</p>${l.exercise.hints.map((h,i)=>`<details><summary>ヒント${i+1}を見る</summary><p>${esc(h)}</p></details>`).join('')}<p><a href="#start">JupyterLabで演習を開く手順 →</a></p></section><h2>振り返り</h2>${list(l.reflection)}<p><a href="#solutions">解いた後に、解答Notebookを開く →</a></p><label class="complete"><input id="complete" type="checkbox" ${state.done.has(l.id)?'checked':''}> このレッスンを学習済みにする</label><div class="bottom-nav">${n?link(lessons[n-1].id,`← ${esc(lessons[n-1].title)}`):link('home','← 学習の全体像')}${n<lessons.length-1?link(lessons[n+1].id,`${esc(lessons[n+1].title)} →`):link('home','学習の全体像へ →')}</div>`;}
function downloads(solutionOnly=false){return `<span class="eyebrow">LEARNING MATERIALS</span><h1>${solutionOnly?'解答を確認する':'教材ダウンロード'}</h1><p>初めて使う場合は、データ・フォント・READMEを含む教材一式をダウンロードして、ZIPを展開してください。Notebookだけではデータを読み込めません。</p><div class="download-item"><h2>教材一式</h2><p>学習サイト、演習・解答Notebook、架空CSV、日本語フォント、環境構築手順を含みます。</p><a class="button primary" href="downloads/python-data-learning.zip" download>教材一式を保存（ZIP） ↓</a></div><div class="download-item"><h2>演習用Notebook</h2><p>全章の問題・ヒント・TODO・自己確認を収録。解答コードや解答の実行出力は含みません。</p><a class="button" href="exercises.ipynb" download>exercises.ipynb を保存 ↓</a></div><div class="download-item"><h2>解答確認用Notebook</h2><p>全章の実行できる解答・結果・考え方を収録しています。</p><details ${solutionOnly?'open':''}><summary>自分で解いたので、解答へのリンクを表示する</summary><p><a class="button" href="solutions.ipynb" download>solutions.ipynb を保存 ↓</a></p></details></div><p><a href="#start">ダウンロード後の環境構築と起動手順 →</a></p>`;}
function start(){return `<span class="eyebrow">GET STARTED</span><h1>JupyterLabで学習を始める</h1><p>${localMode?"このワークスペースでは環境を構築済みです。ターミナルで教材フォルダに移動し、下の起動コマンドを使えます。別の場所へ展開した場合は初回セットアップを行います。":"まず教材ダウンロードからZIPを取得し、すべて展開してください。Pythonの実行には手元のJupyterLabを使います。次の初回セットアップから始めましょう。"}</p><h2>1. 初回だけ、環境を作る</h2><p>Python 3.12を推奨します。ZIPを展開し、ターミナルで展開した<code>python-data-learning</code>フォルダへ移動します。以下はmacOS/Linux用です。Windowsの手順はREADMEにもあります。</p>${code('python3.12 -m venv .venv\nsource .venv/bin/activate\npython -m pip install -r requirements.txt','ターミナル：初回セットアップ')}<details><summary>Windows PowerShellの場合</summary>${code('py -3.12 -m venv .venv\n.venv\\Scripts\\python.exe -m pip install -r requirements.txt\n.venv\\Scripts\\python.exe -m jupyterlab','PowerShell')}</details><h2>2. JupyterLabを起動する</h2>${code('source .venv/bin/activate\npython -m jupyterlab','ターミナル：Notebookを開く')}<p>開いたブラウザの左側に<code>data</code>や<code>exercises.ipynb</code>が見えることを確認し、<code>exercises.ipynb</code>をダブルクリックします。Python 3カーネル（コードを実行するPython）を選択してください。ターミナルは開いたままにします。</p><h2>3. 最初の演習へ進む</h2><p>Notebook内検索（Ctrl+F / Cmd+F）で<code>PD-01</code>を探します。初回は${link('PREP-01','準備レッスン')}のセル操作を確認し、pandas章の準備セルを実行します。次に例題→TODO→自己確認の順で実行します。セルを選んでShift+Enterを押すと実行して次へ進みます。</p><p>保存はCtrl+S / Cmd+S。KernelメニューのRestart Kernelで変数が消えます。再開時は必要な準備セルを実行し直します。「Restart Kernel and Run All Cells」は先頭からの再現確認に使います。未回答のTODOはエラーにならず、未回答と表示されます。</p><h2>サイトも起動する場合</h2><p>別のターミナルで同じ教材フォルダに移動して実行します。</p>${code('python3 serve.py','ターミナル：学習サイト')}<p>ブラウザで<a href="http://localhost:5186/site/">http://localhost:5186/site/</a>を開きます。終了は各ターミナルでCtrl+Cです。</p><h2>うまく動かないとき</h2><ul><li>FileNotFoundError：Notebookとdataフォルダを同じ教材フォルダへ戻します。</li><li>ModuleNotFoundError：仮想環境でインストールし、そのPythonからJupyterLabを起動します。</li><li>NameError：章の準備セルを実行します。画面の上下ではなく、実際の実行順で変数が決まります。</li><li>日本語が四角になる：assetsフォルダを含めて展開し、setup_plotting()を再実行します。seabornのテーマ設定後にも再設定します。</li><li>ポート使用中：サイトは<code>python3 serve.py --port 5187</code>で起動できます。</li></ul>`;}
function render({focus=false}={}){codeIndex=0;state.page=decodeURIComponent(location.hash.slice(1)||'home');const l=lessons.find(x=>x.id===state.page);let html;if(l)html=lessonHTML(l);else if(state.page==='home')html=home();else if(state.page==='downloads'||state.page==='solutions')html=downloads(state.page==='solutions');else if(state.page==='start')html=start();else if(state.page==='python'||state.page==='data')html=C.pages[state.page];else html='<h1>ページが見つかりません</h1><p><a href="#home">学習の全体像へ戻る</a></p>';document.querySelector('#toc').innerHTML=navHTML();const main=document.querySelector('#main');main.innerHTML=html;document.title=(l?`${l.id} ${l.title}`:'分析の手習い')+' — Pythonデータ分析';document.querySelector('aside').classList.toggle('open',state.menu);document.querySelector('#menu').setAttribute('aria-expanded',String(state.menu));document.querySelector('#menu').textContent=state.menu?'学習目次を閉じる':'学習目次を開く';if(focus){main.focus({preventScroll:true});window.scrollTo(0,0);}main.querySelectorAll('[data-copy]').forEach(b=>b.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(document.getElementById(b.dataset.copy).textContent);announce('コードをコピーしました。');}catch(e){announce('コピーできませんでした。コードを選択し、Ctrl+C / Cmd+Cでコピーしてください。');}}));const checkbox=main.querySelector('#complete');if(checkbox)checkbox.addEventListener('change',()=>{if(checkbox.checked)state.done.add(l.id);else state.done.delete(l.id);try{localStorage.setItem(key,JSON.stringify([...state.done]));state.storage=true;}catch(e){state.storage=false;}render();document.querySelector('#complete').focus();announce(state.storage?'学習状況を保存しました。':'このブラウザでは保存できません。今回開いている間だけ記録します。');});}
document.querySelector('#menu').addEventListener('click',()=>{state.menu=!state.menu;document.querySelector('aside').classList.toggle('open',state.menu);document.querySelector('#menu').setAttribute('aria-expanded',String(state.menu));document.querySelector('#menu').textContent=state.menu?'学習目次を閉じる':'学習目次を開く';});
document.querySelector('.skip').addEventListener('click',event=>{event.preventDefault();document.querySelector('#main').focus();});
window.addEventListener('hashchange',()=>{state.menu=false;announce('');render({focus:true});});render();
